version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15.4
    ports:
      - "8500:8500"  
      - "8600:8600/udp"  
    command: "agent -dev -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      CONSUL_BIND_INTERFACE: eth0 
    networks:
      - ts-dkr-network
  
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin@123#
      MYSQL_USER: test
      MYSQL_PASSWORD: test@123#
      MAX_CONNECTIONS: 100000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - ts-dkr-network
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ts-dkr-network

  ts-new-gateway:
    image: ts-new-gateway:latest
    ports:
      - "8888:8888"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul

  ts-ui-service:
    image: ts-ui-dashboard:latest
    ports:
      - "8080:8080"
    depends_on:
      ts-new-gateway:
        condition: service_started
    networks:
      - ts-dkr-network
    environment:
      GATEWAY_HOST: ts-new-gateway

  ts-order-service:
    image: ts-order-service:latest
    ports:
      - "8900:8900"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq


  ts-food-service:
    image: ts-food-service:latest
    ports:
      - "8896:8896"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-cancel-service:
    image: ts-cancel-service:latest
    ports:
      - "8891:8891"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq
  
  ts-admin-service:
    image: ts-admin-service:latest
    ports:
      - "8887:8887"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq
  
  ts-assurance-service:
    image: ts-assurance-service:latest
    ports:
      - "8889:8889"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-auth-service:
    image: ts-auth-service:latest
    ports:
      - "8890:8890"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-config-service:
    image: ts-config-service:latest
    ports:
      - "8892:8892"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-consign-service:
    image: ts-consign-service:latest
    ports:
      - "8893:8893"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-contacts-service:
    image: ts-contacts-service:latest
    ports:
      - "8894:8894"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-delivery-service:
    image: ts-delivery-service:latest
    ports:
      - "8895:8895"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-notification-service:
    image: ts-notification-service:latest
    ports:
      - "8898:8898"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-order-related-service:
    image: ts-order-related-service:latest
    ports:
      - "8899:8899"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-preserve-service:
    image: ts-preserve-service:latest
    ports:
      - "8901:8901"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-price-service:
    image: ts-price-service:latest
    ports:
      - "8902:8902"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-rebook-service:
    image: ts-rebook-service:latest
    ports:
      - "8903:8903"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-route-service:
    image: ts-route-service:latest
    ports:
      - "8904:8904"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-security-service:
    image: ts-security-service:latest
    ports:
      - "8905:8905"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-station-service:
    image: ts-station-service:latest
    ports:
      - "8906:8906"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

  ts-travel-service:
    image: ts-travel-service:latest
    ports:
      - "8907:8907"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq
      
  ts-user-service:
    image: ts-user-service:latest
    ports:
      - "8908:8908"
    depends_on:
      ts-new-gateway:
        condition: service_started
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - ts-dkr-network
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql
      RABBIT_HOST: rabbitmq

volumes:
  mysql_data:
  rabbitmq_data:
    driver: local

networks:
  ts-dkr-network:
    driver: bridge