server:
  port: 8892
spring:
  application:
    name: ts-config-service
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${random.int[1,99]}
        prefer-ip-address: true
      host: localhost
      port: 8500
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin@123#
    url: jdbc:mysql://localhost:3306/ts-config-service?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
