server:
  port: 8890
spring:
  application:
    name: ts-auth-service
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${random.int[1,99]}
        prefer-ip-address: true
      host: ${CONSUL_HOST:localhost}
      port: 8500
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: AVNS_SuKJgZrVfCXlWtmbnrj
    url: jdbc:mysql://db-mysql-nyc3-40046-do-user-15314830-0.c.db.ondigitalocean.com:25060/ts-auth-service?createDatabaseIfNotExist=true
    username: doadmin
  jpa:
    hibernate:
      ddl-auto: update
